#!/bin/bash

# Function to run a test case
run_test() {
    echo "Running test: $1"
    if "$@"; then
        echo "Test passed!"
    else
        echo "Test failed!"
    fi
    echo
}

# Test cases
run_test ./pipe ls

run_test "./pipe ls | wc"

run_test "./pipe ls | grep \"pipe\" | wc"

run_test "./pipe echo \"Hello\" | tr '[:upper:]' '[:lower:]'"

run_test "./pipe cat < input.txt"

run_test "./pipe echo \"Testing\" > output.txt"

run_test "./pipe cat < input.txt | grep \"pattern\" > output.txt"

run_test ./pipe invalid_program

run_test "./pipe ls -l | grep \"file\" | awk '{print $9}' | sort"

run_test "./pipe ls | wc &"

# Add more test cases as needed

echo "All test cases completed."
